site_name: Karavy Docs

nav:
  - Home: index.md
  - Installazione:
      - Karavy Demo: karavy-demo.md

theme:
  name: readthedocs

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

